import type { Metadata } from 'next';
import { Carme } from 'next/font/google';
import './globals.css';

const carme = Carme({
  weight: '400',
  variable: '--font-carme',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${carme.variable} antialiased bg-background no-scrollbar`}>
        <div>{children}</div>
      </body>
    </html>
  );
}
